interfaces:
  - name: e0/0
    ip_address: 192.168.1.2
    mask: 255.255.255.0
    description: mgt_interface
    active: true
  - name: e0/1
    ip_address: 192.168.3.1
    mask: 255.255.255.0
    description: LAN2
    active: true
  - name: e0/2
    ip_address: 192.168.0.2
    mask: 255.255.255.252
    description: to_R1
    active: true

dhcp_relay_agent:
  - interface: e0/1
    ip_helper: 192.168.2.1

ospf:
  process_id: 1
  router_id: 2.2.2.2
  passive_interfaces:
    - e0/0
    - e0/1
  area:
    - area_id: 0
      networks:
        - ip: 192.168.1.0
          mask: 0.0.0.255
        - ip: 192.168.3.0
          mask: 0.0.0.255
        - ip: 192.168.0.0
          mask: 0.0.0.3
